Fix printf invokation in bfopt
bfopt tool assumes `std::size_t` can be printed using the `%lu` format specifier, which breaks the build on platforms where this assumption does not hold

```
tools/bfopt.cc: In function ‘void run(const std::vector<Op*>&)’:
tools/bfopt.cc:293:19: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 5 has type ‘size_t {aka unsigned int}’ [-Werror=format=]
                 pc);
                   ^
```