Fix mcfunction type limits
`mcf_char_to_string` clearly assumes signed char, however this is not guaranteed by the standard and will cause an error on platforms, where this assumption does not hold

```
target/mcfunction.c: In function ‘mcf_char_to_string’:
target/mcfunction.c:141:10: error: comparison is always true due to limited range of data type [-Werror=type-limits]
   if ((c >= 0 && c < 32) || c == 127)
          ^~
```